# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CAIRODialog
                                 A QGIS plugin
 AERMOD, AERMAP, and AERPLOT input file compiler and analysis tool with risk assessment
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-02-23
        git sha              : $Format:%H$
        copyright            : (C) 2025 by MSc Dominik Subotić
        email                : suboticdominik@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from PyQt5.QtWidgets import QMessageBox
from qgis.PyQt.QtWidgets import (QComboBox, QLineEdit, QDialog, QVBoxLayout, QHBoxLayout, QPushButton, QLabel,
                                 QFileDialog, QTextEdit, QTabWidget, QWidget, QCheckBox, QTableWidget,
                                 QTableWidgetItem, QListWidget)
from qgis.PyQt.QtGui import QFont, QPixmap, QMovie
from qgis.PyQt.QtCore import Qt, QTimer, QProcess, QUrl, pyqtSignal, QObject
from qgis._core import QgsVectorLayer, QgsGeometry, QgsPointXY, QgsCoordinateReferenceSystem, QgsCoordinateTransform, \
    QgsProject
from qgis.utils import iface
from PyQt5.QtGui import QDesktopServices
import os
import csv
import shutil
import textwrap
import time

from .CAIRO import (ReceptorGridDialog, SourceTypeDialog, GroupDialog)


class ProcessManager(QObject):
    all_finished = pyqtSignal()

    def __init__(self, parent=None):
        super().__init__(parent)
        self.processes = []  # Will store tuples of (process, fwd_path)
        self.completed_count = 0

    def add_process(self, process, fwd_path):
        self.processes.append((process, fwd_path))
        process.finished.connect(self.on_process_finished)  # Connect to the QProcess object

    def on_process_finished(self, exit_code, exit_status):
        self.completed_count += 1
        if self.completed_count == len(self.processes):
            self.all_finished.emit()


class RiskAssessmentDialog(QDialog):

    def __init__(self, plugin_dir, iface, parent=None):
        super(RiskAssessmentDialog, self).__init__(parent)
        self.plugin_dir = plugin_dir
        self.iface = iface
        self.process_manager = ProcessManager(self)
        self.setWindowTitle("CAIRO © ~ Air Risk Assessment Module ©")
        self.setGeometry(100, 100, 725, 480)

        self.tab_widget = QTabWidget()

        self.setup_tab = QWidget()
        self.setup_layout = QVBoxLayout()

        top_row_layout = QHBoxLayout()

        image_path = os.path.join(self.plugin_dir, "CAIRO.PNG")
        self.image_label = QLabel()
        pixmap = QPixmap(image_path)
        if not pixmap.isNull():
            self.image_label.setPixmap(pixmap)
            self.image_label.setAlignment(Qt.AlignLeft)
        else:
            self.image_label.setText("Image not found!")
        top_row_layout.addWidget(self.image_label)

        top_row_layout.addStretch()

        self.info_label = QLabel(
            "Air Risk Assessment Module ©\n"
            "CAIRO © for AERMOD, 2025.\n"
            "MSc Dominik Subotić @UNIVPM\n\n"
            "Hover over labels for information\n"
            "Requires running AERPLOT using CAIRO for 1h and ANNUAL or PERIOD averaging period"
        )
        self.info_label.setAlignment(Qt.AlignLeft | Qt.AlignVCenter)
        top_row_layout.addWidget(self.info_label)

        self.setup_layout.addLayout(top_row_layout)

        # Left and right side layout for receptors and site model
        receptor_site_layout = QHBoxLayout()

        # Left side: Receptors
        receptor_layout = QVBoxLayout()
        self.receptor_label = QLabel("Receptors")
        self.receptor_label.setFont(QFont("Arial", 12, QFont.Bold))
        self.receptor_combobox = QComboBox()
        self.receptor_combobox.addItems([
            "Adults and Children", "Adults, Children, Teenagers and Seniors", "Adults", "Workers"
        ])
        self.critical_receptor_checkbox = QCheckBox("Use most critical receptor for toxic contaminants")
        self.receptor_combobox.currentIndexChanged.connect(self.update_checkbox_state)
        self.update_checkbox_state()

        receptor_layout.addWidget(self.receptor_label)
        receptor_layout.addWidget(self.receptor_combobox)
        receptor_layout.addWidget(self.critical_receptor_checkbox)

        # Right side: Site Model
        site_model_layout = QVBoxLayout()
        self.site_model_label = QLabel("Site Model")
        self.site_model_label.setFont(QFont("Arial", 12, QFont.Bold))
        self.outdoor_vapor_checkbox = QCheckBox("Outdoor vapor inhalation")
        self.indoor_vapor_checkbox = QCheckBox("Indoor vapor inhalation")

        site_model_layout.addWidget(self.site_model_label)
        site_model_layout.addWidget(self.outdoor_vapor_checkbox)
        site_model_layout.addWidget(self.indoor_vapor_checkbox)

        # Add left and right layouts to the main horizontal layout
        receptor_site_layout.addLayout(receptor_layout)
        receptor_site_layout.addLayout(site_model_layout)

        self.setup_layout.addLayout(receptor_site_layout)

        # Plotting Options label
        plotting_label = QLabel("Plotting Options")
        plotting_label.setFont(QFont("Arial", 12, QFont.Bold))
        self.setup_layout.addWidget(plotting_label)

        # UTM and Hemisphere layout
        utm_hemisphere_layout = QHBoxLayout()

        # Left side: UTM and Hemisphere
        utm_hemisphere_left_layout = QVBoxLayout()
        utm_label = QLabel("UTM Zone:")
        self.utm_textbox = QLineEdit()
        hemisphere_label = QLabel("Hemisphere:")
        self.hemisphere_combo = QComboBox()
        self.hemisphere_combo.addItems(["inNorthernHemisphere", "inSouthernHemisphere"])

        utm_hemisphere_left_layout.addWidget(utm_label)
        utm_hemisphere_left_layout.addWidget(self.utm_textbox)
        utm_hemisphere_left_layout.addWidget(hemisphere_label)
        utm_hemisphere_left_layout.addWidget(self.hemisphere_combo)

        # Right side: Minimum Bin, Maximum Bin, and Custom Bins
        bins_layout = QVBoxLayout()
        minimum_bin_label = QLabel("Minimum Bin:")
        self.minimum_bin_textbox = QLineEdit("data")
        minimum_bin_label.setToolTip("Default bins = data")
        maximum_bin_label = QLabel("Maximum Bin:")
        maximum_bin_label.setToolTip("Default bins = data")
        self.maximum_bin_textbox = QLineEdit("data")
        custom_bins_label = QLabel("Custom Bins:")
        custom_bins_label.setToolTip("Eleven bins, comma separated; Default bins = na")
        self.custom_bins_textbox = QLineEdit("na")

        bins_layout.addWidget(minimum_bin_label)
        bins_layout.addWidget(self.minimum_bin_textbox)
        bins_layout.addWidget(maximum_bin_label)
        bins_layout.addWidget(self.maximum_bin_textbox)
        bins_layout.addWidget(custom_bins_label)
        bins_layout.addWidget(self.custom_bins_textbox)

        # Add left and right layouts to the main horizontal layout
        utm_hemisphere_layout.addLayout(utm_hemisphere_left_layout)
        utm_hemisphere_layout.addLayout(bins_layout)
        spacer_label1 = QLabel("")  # First spacer
        spacer_label2 = QLabel("")  # Second spacer
        utm_hemisphere_left_layout.addWidget(spacer_label1)
        utm_hemisphere_left_layout.addWidget(spacer_label2)

        self.setup_layout.addLayout(utm_hemisphere_layout)

        # Add coordinates section
        coordinates_label = QLabel("Specific Coordinate Asessment:")
        self.setup_layout.addWidget(coordinates_label)

        self.coordinates_table = QTableWidget()
        self.coordinates_table.setColumnCount(3)
        self.coordinates_table.setHorizontalHeaderLabels(["Easting", "Northing", "Receptor Name"])
        self.coordinates_table.setMinimumHeight(150)
        self.coordinates_table.setColumnWidth(0, 200)
        self.coordinates_table.setColumnWidth(1, 200)
        self.coordinates_table.setColumnWidth(2, 250)
        self.setup_layout.addWidget(self.coordinates_table)

        add_coordinate_button = QPushButton("Add Coordinate")
        add_coordinate_button.setToolTip("Add Coordinates for specific output; Maximum value is included by default")
        add_coordinate_button.clicked.connect(self.add_coordinate_row)
        self.setup_layout.addWidget(add_coordinate_button)

        self.setup_tab.setLayout(self.setup_layout)

        self.exposure_factors_tab = QWidget()
        self.exposure_layout = QVBoxLayout()
        self.exposure_table = QTableWidget()
        self.exposure_table.setRowCount(11)
        self.exposure_table.setColumnCount(8)
        self.exposure_table.setHorizontalHeaderLabels([
            "Exposure parameters", "Symbol", "Unit", "Children", "Teenagers", "Adults", "Senior", "Workers"
        ])

        self.exposure_table.verticalHeader().setVisible(False)

        merged_rows = [0, 5, 8]
        merged_labels = ["General factors", "Outdoor Vapor Inhalation", "Indoor Vapor Inhalation"]
        bold_font = QFont()
        bold_font.setBold(True)

        for i, row in enumerate(merged_rows):
            item = QTableWidgetItem(merged_labels[i])
            item.setFlags(item.flags() & ~Qt.ItemIsEditable)
            item.setFont(bold_font)
            self.exposure_table.setItem(row, 0, item)
            self.exposure_table.setSpan(row, 0, 1, 8)

        data_rows = [
            (1, "Body Weight", "BW", "kg", [15, 15, 70, 70, 70]),
            (2, "Averaging time for carcinogens", "AT", "y", [70, 70, 70, 70, 70]),
            (3, "Exposure duration", "ED", "y", [6, 10, 24, 5, 25]),
            (4, "Exposure frequency", "EF", "d/y", [350, 350, 350, 350, 250]),
            (6, "Daily frequency", "EFgo", "h/d", [24, 0.5, 24, 1.9, 8]),
            (7, "Vapor inhalation rate", "Bo", "m³/h", [0.7, 0.7, 0.9, 0.9, 2.5]),
            (9, "Daily frequency", "EFgi", "h/d", [24, 19.6, 24, 22.4, 8]),
            (10, "Vapor inhalation rate", "Bi", "m³/h", [0.7, 0.7, 0.9, 0.9, 0.9]),
        ]

        for row, label, symbol, unit, values in data_rows:
            for col, text in enumerate([label, symbol, unit]):
                item = QTableWidgetItem(text)
                item.setFlags(item.flags() & ~Qt.ItemIsEditable)
                self.exposure_table.setItem(row, col, item)
            for col, value in enumerate(values, start=3):
                item = QTableWidgetItem(str(value))
                item.setFlags(item.flags() | Qt.ItemIsEditable)
                self.exposure_table.setItem(row, col, item)
        self.exposure_table.setColumnWidth(0, 200)
        self.exposure_table.setColumnWidth(1, 50)
        self.exposure_table.setColumnWidth(2, 50)
        self.exposure_table.setColumnWidth(3, 75)
        self.exposure_table.setColumnWidth(4, 75)
        self.exposure_table.setColumnWidth(5, 75)
        self.exposure_table.setColumnWidth(6, 75)
        self.exposure_table.setColumnWidth(7, 75)

        self.exposure_layout.addWidget(self.exposure_table)

        exposure_text = (
            "(a) For intense physical activity in a residential outdoor scenario,"
            " a Bo value of 1.5 m³/h for adults and 1.0 m³/h for children is suggested.\n"
            "(b) For workers it is suggested to use, in the case of hard physical activity,"
            " a Bo value of 2.5 m³/h, for moderate activity 1.5 m³/h and for sedentary activity 0.9 m³/h.\n"
            "(c) For high physical activity in a recreational scenario a Bo value of "
            "3.2 m³/h for adults and 1.9 m³/h for children can be used.\n"
            "A daily frequency exposure (EFg) of 3 h/day can be used. (ISPRA, 2016.)\n\n\n"
        )

        # Create a QLabel for the text
        exposure_info_label = QLabel(exposure_text)
        exposure_info_label.setWordWrap(True)  # Enable word wrap for long text
        exposure_info_label.setStyleSheet("font-size: 10pt;")  # Adjust font size if needed

        # Add the label to the exposure layout
        self.exposure_layout.addWidget(exposure_info_label)

        self.exposure_factors_tab.setLayout(self.exposure_layout)

        self.run_tab = QWidget()
        self.run_layout = QVBoxLayout()

        self.group_name_label = QLabel("Group names")
        self.group_name_label.setToolTip("Enter the name of the AERMOD groups, space separated;\n"
                                         "Needed to fetch the corresponding AERMOD output")
        self.group_name_textbox = QLineEdit()

        self.pollutant_search_label = QLabel("Search Pollutants")
        self.pollutant_search_label.setToolTip("Type to filter pollutants by name (partial matches allowed)")
        self.pollutant_search_input = QLineEdit()
        self.pollutant_search_input.setPlaceholderText("Enter pollutant name or part of it...")
        self.pollutant_search_input.textChanged.connect(self.filter_pollutant_list)  # NEW: Connect to filter function

        self.pollutant_list = QListWidget()
        self.all_pollutants = []
        self.populate_pollutant_list()
        self.pollutant_list.itemClicked.connect(self.on_pollutant_selected)

        self.run_button = QPushButton("Run Risk Assessment")
        self.run_button.setToolTip("Click to execute the risk assessment with the selected contaminant;\n"
                                   "Select the main project folder containing aerplot folders and RANK files")
        self.run_button.clicked.connect(self.run_risk_assessment)

        self.run_layout.addWidget(self.group_name_label)
        self.run_layout.addWidget(self.group_name_textbox)
        self.run_layout.addWidget(self.pollutant_search_label)
        self.run_layout.addWidget(self.pollutant_search_input)
        self.run_layout.addWidget(self.pollutant_list)
        self.run_layout.addWidget(self.run_button)
        self.run_tab.setLayout(self.run_layout)

        self.tab_widget.addTab(self.setup_tab, "Setup")
        self.tab_widget.addTab(self.exposure_factors_tab, "Exposure Factors")
        self.tab_widget.addTab(self.run_tab, "Scope")

        main_layout = QVBoxLayout()
        main_layout.addWidget(self.tab_widget)
        self.setLayout(main_layout)

        self.selected_pollutant = None
        self.selected_row_index = None

        # New Postprocessing Tab
        self.post_tab = QWidget()
        self.post_layout = QVBoxLayout()

        quantitative_label = QLabel("Quantitative Population Risk Assessment")
        quantitative_label.setFont(QFont("Arial", 12, QFont.Bold))
        self.post_layout.addWidget(quantitative_label)

        infor_label = QLabel("* Requires running risk assesment previously")
        self.post_layout.addWidget(infor_label)

        self.add_shp_button = QPushButton("Add GEOSTAT Shape File")
        self.add_shp_button.setToolTip("Choose Geostat or similar territory and population data .shp file")
        self.add_shp_button.clicked.connect(self.load_shp_file)
        self.post_layout.addWidget(self.add_shp_button)

        self.shp_path_label = QLabel("No .shp file selected")
        self.post_layout.addWidget(self.shp_path_label)

        area_label = QLabel("Area Attribute")
        area_label.setToolTip("Select the attribute defining the area type (e.g., 'istat_COMU' for communes)")
        self.post_layout.addWidget(area_label)
        self.area_attribute_combo = QComboBox()
        self.area_attribute_combo.addItem("Load a .shp file first")
        self.area_attribute_combo.setEnabled(False)
        self.post_layout.addWidget(self.area_attribute_combo)

        population_label = QLabel("Population Attribute")
        population_label.setToolTip("Select the attribute for population type (e.g., 'TOTAL', 'MEN', 'WOMEN')")
        self.post_layout.addWidget(population_label)
        self.population_attribute_combo = QComboBox()
        self.population_attribute_combo.addItem("Load a .shp file first")
        self.population_attribute_combo.setEnabled(False)
        self.post_layout.addWidget(self.population_attribute_combo)

        spacer_label1 = QLabel("")
        spacer_label2 = QLabel("")
        spacer_label3 = QLabel("")

        self.post_layout.addWidget(spacer_label1)
        self.post_layout.addWidget(spacer_label2)
        self.post_layout.addWidget(spacer_label3)

        self.run_postprocessing_button = QPushButton("Run")
        self.run_postprocessing_button.setToolTip("Calculate average risk and concentration per area")
        self.run_postprocessing_button.clicked.connect(self.run_population_risk_assessment)
        self.post_layout.addWidget(self.run_postprocessing_button)

        self.post_tab.setLayout(self.post_layout)

        self.tab_widget.addTab(self.setup_tab, "Setup")
        self.tab_widget.addTab(self.exposure_factors_tab, "Exposure Factors")
        self.tab_widget.addTab(self.run_tab, "Scope")
        self.tab_widget.addTab(self.post_tab, "Postprocessing")

        self.shp_path = None
        self.project_folder = None

    def load_shp_file(self):
        shp_path = QFileDialog.getOpenFileName(self, "Select .shp File", "", "Shapefiles (*.shp)")[0]
        if not shp_path:
            return

        self.shp_path = shp_path
        self.shp_path_label.setText(f"Selected: {os.path.basename(shp_path)}")
        self.iface.messageBar().pushMessage("Info", f"Loaded .shp file: {shp_path}", level=0)

        layer = QgsVectorLayer(shp_path, "temp_layer", "ogr")
        if not layer.isValid():
            self.iface.messageBar().pushMessage("Error", f"Invalid .shp file: {shp_path}", level=2)
            self.shp_path = None
            return

        field_names = [field.name() for field in layer.fields()]

        self.area_attribute_combo.clear()
        self.population_attribute_combo.clear()
        self.area_attribute_combo.addItems(field_names)
        self.population_attribute_combo.addItems(field_names)
        self.area_attribute_combo.setEnabled(True)
        self.population_attribute_combo.setEnabled(True)

    def update_checkbox_state(self):
        selected_index = self.receptor_combobox.currentIndex()
        if selected_index in [0, 1]:
            self.critical_receptor_checkbox.setEnabled(True)
        else:
            self.critical_receptor_checkbox.setEnabled(False)
            self.critical_receptor_checkbox.setChecked(False)

    def populate_pollutant_list(self):
        database_path = os.path.join(self.plugin_dir, "database.csv")
        if os.path.exists(database_path):
            with open(database_path, 'r', encoding='utf-8') as csvfile:
                reader = csv.reader(csvfile, delimiter=';')
                rows = list(reader)
                if len(rows) > 1:
                    self.all_pollutants = [row[1] for row in rows[1:] if len(row) > 1]
                    self.pollutant_list.clear()
                    for pollutant in self.all_pollutants:
                        self.pollutant_list.addItem(pollutant)
        else:
            print("Warning: database.csv not found in plugin directory")

    def filter_pollutant_list(self, text):
        self.pollutant_list.clear()
        search_text = text.lower().strip()
        if not search_text:
            for pollutant in self.all_pollutants:
                self.pollutant_list.addItem(pollutant)
        else:
            filtered_pollutants = [p for p in self.all_pollutants if search_text in p.lower()]
            for pollutant in filtered_pollutants:
                self.pollutant_list.addItem(pollutant)

    def on_pollutant_selected(self, item):
        self.selected_pollutant = item.text()
        self.selected_row_index = next((i for i, p in enumerate(self.all_pollutants) if p == item.text()),
                                       None) + 1

    def add_coordinate_row(self):
        row_position = self.coordinates_table.rowCount()
        self.coordinates_table.insertRow(row_position)

    def run_risk_assessment(self):
        dialog = RiskAssessmentDialog(self.plugin_dir, self)
        dialog.show()
        project_folder = QFileDialog.getExistingDirectory(self, "Select Project Folder")
        if not project_folder:
            return
        self.iface.messageBar().pushMessage("Info", "Running risk assessment...", level=0)
        if not project_folder:
            return
        self.project_folder = project_folder

        groups = self.group_name_textbox.text().split()
        outdoor_checked = self.outdoor_vapor_checkbox.isChecked()
        indoor_checked = self.indoor_vapor_checkbox.isChecked()
        utm_zone = self.utm_textbox.text()
        hemisphere = self.hemisphere_combo.currentText()

        coordinates = []
        for row in range(self.coordinates_table.rowCount()):
            easting_item = self.coordinates_table.item(row, 0)
            northing_item = self.coordinates_table.item(row, 1)
            if easting_item and northing_item:
                try:
                    easting = float(easting_item.text())
                    northing = float(northing_item.text())
                    coordinates.append((easting, northing))
                except ValueError:
                    self.iface.messageBar().pushMessage("Warning", f"Invalid coordinate at row {row + 1}", level=1)

        database_path = os.path.join(self.plugin_dir, "database.csv")
        with open(database_path, 'r') as csvfile:
            reader = csv.reader(csvfile, delimiter=';')
            rows = list(reader)
            for row in rows[1:]:
                if row[1] == self.selected_pollutant:
                    arfc = row[3]
                    iur = row[2]
                    rfc = row[4]
                    break
            else:
                self.iface.messageBar().pushMessage("Error", "Pollutant not found in database.csv", level=2)
                return

        receptor_groups = {
            0: [0, 2],  # Adults and Children: Children (0), Adults (2)
            1: [0, 1, 2, 3],  # Adults, Children, Teenagers, Seniors
            2: [2],  # Adults
            3: [4]  # Workers
        }
        selected_receptors = receptor_groups[self.receptor_combobox.currentIndex()]

        avg_periods = {group: {"1H": False, "ANNUAL": False, "PERIOD": False} for group in groups}

        for group in groups:
            aerplot_chronic_subfolder = None
            for subfolder in [f"aerplot_{group}_ANNUAL", f"aerplot_{group}_PERIOD"]:
                if os.path.exists(os.path.join(project_folder, subfolder)):
                    aerplot_chronic_subfolder = subfolder
                    break

            if not aerplot_chronic_subfolder:
                self.iface.messageBar().pushMessage("Warning", f"No ANNUAL or PERIOD subfolder found for group {group}",
                                                    level=1)
                continue

            if "ANNUAL" in aerplot_chronic_subfolder:
                avg_period = "ANNUAL"
            else:
                avg_period = "PERIOD"
            avg_periods[group]["chronic"] = avg_period
            avg_periods[group][avg_period] = True
            aerplot_acute_subfolder = f"aerplot_{group}_1"
            aerplot_chronic_path = os.path.join(project_folder, aerplot_chronic_subfolder)
            aerplot_acute_path = os.path.join(project_folder, aerplot_acute_subfolder)

            if not os.path.exists(aerplot_acute_path):
                self.iface.messageBar().pushMessage("Warning", f"{aerplot_acute_subfolder} not found", level=1)
                continue

            risk_main_folder = os.path.join(project_folder, "RISK")
            os.makedirs(risk_main_folder, exist_ok=True)
            risk_subfolder = f"risk_{group}"
            risk_path = os.path.join(risk_main_folder, risk_subfolder)
            os.makedirs(risk_path, exist_ok=True)

            site_types = []
            if outdoor_checked:
                site_types.append("outdoor")
            if indoor_checked:
                site_types.append("indoor")

            for site_type in site_types:
                site_path = os.path.join(risk_path, site_type)
                os.makedirs(site_path, exist_ok=True)

                if iur != '' and site_type in ["outdoor", "indoor"]:
                    r_path = os.path.join(site_path, "R")
                    os.makedirs(r_path, exist_ok=True)
                    aerplot_path = aerplot_chronic_path
                    self.process_fwd_subfolder(
                        fwd_path=r_path,
                        aerplot_path=aerplot_path,
                        group=group,
                        site_type=site_type,
                        risk_type="R",
                        selected_receptors=selected_receptors,
                        arfc=arfc,
                        iur=iur,
                        rfc=rfc,
                        coordinates=coordinates,
                        utm_zone=utm_zone,
                        hemisphere=hemisphere,
                        avg_period=avg_period
                    )

                if rfc != '' and site_type in ["outdoor", "indoor"]:
                    hi_path = os.path.join(site_path, "HI")
                    os.makedirs(hi_path, exist_ok=True)
                    aerplot_path = aerplot_chronic_path
                    self.process_fwd_subfolder(
                        fwd_path=hi_path,
                        aerplot_path=aerplot_path,
                        group=group,
                        site_type=site_type,
                        risk_type="HI",
                        selected_receptors=selected_receptors,
                        arfc=arfc,
                        iur=iur,
                        rfc=rfc,
                        coordinates=coordinates,
                        utm_zone=utm_zone,
                        hemisphere=hemisphere,
                        avg_period=avg_period
                    )

                if arfc != '' and site_type in ["outdoor", "indoor"]:
                    acute_path = os.path.join(site_path, "ACUTE")
                    os.makedirs(acute_path, exist_ok=True)
                    aerplot_path = aerplot_acute_path
                    self.process_fwd_subfolder(
                        fwd_path=acute_path,
                        aerplot_path=aerplot_path,
                        group=group,
                        site_type=site_type,
                        risk_type="ACUTE",
                        selected_receptors=selected_receptors,
                        arfc=arfc,
                        iur=iur,
                        rfc=rfc,
                        coordinates=coordinates,
                        utm_zone=utm_zone,
                        hemisphere=hemisphere,
                        avg_period="1H"
                    )

        self.create_summary_file(project_folder, groups, outdoor_checked, indoor_checked, avg_periods)

        def on_all_finished():
            for _, fwd_path in self.process_manager.processes:
                exe_path = os.path.join(fwd_path, "aerplot.exe")
                if os.path.exists(exe_path):
                    try:
                        os.remove(exe_path)
                    except Exception as e:
                        self.iface.messageBar().pushMessage("Warning",
                                                            f"Failed to delete aerplot.exe in {fwd_path}: {str(e)}",
                                                            level=1)

            QMessageBox.information(self, "Risk Assessment", "Risk Assessment Complete!")

        self.process_manager.all_finished.connect(on_all_finished)

        if not self.process_manager.processes:
            on_all_finished()

    def run_population_risk_assessment(self):
        """Calculate average risk and concentration per area using .shp file, prompting for project folder."""
        # List to collect missing items
        missing_items = []

        # Check UTM textbox
        if not self.utm_textbox.text().strip():
            missing_items.append("UTM Zone")

        # Check site model (at least one checkbox)
        if not (self.outdoor_vapor_checkbox.isChecked() or self.indoor_vapor_checkbox.isChecked()):
            missing_items.append("Site Model (Outdoor or Indoor Vapor Inhalation)")

        # Check group name
        if not self.group_name_textbox.text().strip():
            missing_items.append("Group Name")

        # Check pollutant selection
        if not self.selected_pollutant:
            missing_items.append("Pollutant")

        # Check shapefile
        if not self.shp_path:
            missing_items.append("Shapefile")

        # If any items are missing, show a message box and return
        if missing_items:
            QMessageBox.warning(self, "Missing Inputs",
                                "Please provide the following before running the assessment:\n- " +
                                "\n- ".join(missing_items))
            return

        # If all checks pass, proceed with folder selection
        project_folder = QFileDialog.getExistingDirectory(self, "Select Project Folder Containing RISK Folder")
        if not project_folder:
            self.iface.messageBar().pushMessage("Info", "Population risk assessment cancelled.", level=0)
            return
        self.project_folder = project_folder

        if not os.path.exists(os.path.join(self.project_folder, "RISK")):
            self.iface.messageBar().pushMessage("Error", "Selected folder does not contain a 'RISK' subfolder.",
                                                level=2)
            return
        # Fetch pollutant data from database.csv
        database_path = os.path.join(self.plugin_dir, "database.csv")
        with open(database_path, 'r') as csvfile:
            reader = csv.reader(csvfile, delimiter=';')
            rows = list(reader)
            for row in rows[1:]:
                if row[1] == self.selected_pollutant:
                    arfc = row[3]
                    iur = row[2]
                    rfc = row[4]
                    break
            else:
                self.iface.messageBar().pushMessage("Error", "Pollutant not found in database.csv", level=2)
                return

        area_attr = self.area_attribute_combo.currentText()
        pop_attr = self.population_attribute_combo.currentText()
        if not area_attr or not pop_attr or area_attr == "Load .shp file first" or pop_attr == "Load .shp file first":
            self.iface.messageBar().pushMessage("Error", "Please select valid area and population attributes", level=2)
            return

        # Get UTM zone and hemisphere from Setup tab
        utm_zone = self.utm_textbox.text().strip()
        hemisphere = self.hemisphere_combo.currentText()
        if not utm_zone or not utm_zone.isdigit():
            self.iface.messageBar().pushMessage("Error", "Please enter a valid UTM zone number in the Setup tab",
                                                level=2)
            return

        epsg_base = "326" if hemisphere == "inNorthernHemisphere" else "327"
        plt_epsg = f"EPSG:{epsg_base}{utm_zone.zfill(2)}"
        self.iface.messageBar().pushMessage("Debug", f"Using .plt CRS: {plt_epsg}", level=0)

        self.iface.messageBar().pushMessage("Info", "Running population risk assessment...", level=0)

        # Load .shp file as a vector layer
        layer = QgsVectorLayer(self.shp_path, "population_layer", "ogr")
        if not layer.isValid():
            self.iface.messageBar().pushMessage("Error", f"Invalid .shp file: {self.shp_path}", level=2)
            return
        shp_crs = layer.crs()  # EPSG:4326
        self.iface.messageBar().pushMessage("Debug",
                                            f"Loaded .shp with {layer.featureCount()} features,CRS: {shp_crs.authid()}",
                                            level=0)

        # Set up coordinate transform
        plt_crs = QgsCoordinateReferenceSystem(plt_epsg)
        if not plt_crs.isValid():
            self.iface.messageBar().pushMessage("Error", f"Invalid UTM CRS: {plt_epsg}", level=2)
            return
        transform = QgsCoordinateTransform(plt_crs, shp_crs, QgsProject.instance())

        # Pre-aggregate total population by istat_COMU across all polygons
        areas = {}  # {istat_COMU: {'population': total_pop, 'geometries': [geom1, geom2, ...]}}
        for feature in layer.getFeatures():
            area_name = feature[area_attr]
            if not area_name:
                continue
            pop = feature[pop_attr]
            try:
                pop = float(pop) if pop else 0
            except (ValueError, TypeError):
                pop = 0
            geom = feature.geometry()
            if not geom or geom.isEmpty():
                continue
            if area_name not in areas:
                areas[area_name] = {'population': 0, 'geometries': []}
            areas[area_name]['population'] += pop
            areas[area_name]['geometries'].append(geom)
        self.iface.messageBar().pushMessage("Debug", f"Aggregated {len(areas)} unique areas from .shp", level=0)

        # Get groups and site types from run_tab
        groups = self.group_name_textbox.text().split()
        site_types = ["outdoor"] if self.outdoor_vapor_checkbox.isChecked() else []
        if self.indoor_vapor_checkbox.isChecked():
            site_types.append("indoor")
        risk_types = []
        if iur and iur != '0':
            risk_types.append("R")
        if rfc and rfc != '0':
            risk_types.append("HI")
        if arfc and arfc != '0':
            risk_types.append("ACUTE")
        if not risk_types:
            self.iface.messageBar().pushMessage("Error", "No valid risk types available for this pollutant", level=2)
            return
        avg_periods = {}
        # Process each combination
        for group in groups:
            for site_type in site_types:
                for risk_type in risk_types:
                    # Paths to .plt files
                    risk_path = os.path.join(self.project_folder, "RISK", f"risk_{group}", site_type, risk_type)
                    avg_period = "1H" if risk_type == "ACUTE" else ("ANNUAL" if os.path.exists(
                        os.path.join(self.project_folder, f"aerplot_{group}_ANNUAL")) else "PERIOD")
                    risk_plt = f"RISK_{'OUT' if site_type == 'outdoor' else 'IND'}_{risk_type}_{group}_{avg_period}.plt"
                    risk_plt_path = os.path.join(risk_path, risk_plt)
                    conc_plt = f"PLOT{avg_period}_{group}.plt"
                    conc_plt_path = os.path.join(risk_path, conc_plt)

                    if not os.path.exists(risk_plt_path) or not os.path.exists(conc_plt_path):
                        self.iface.messageBar().pushMessage("Warning",
                                                            f"Missing .plt files: {risk_plt_path} or {conc_plt_path}",
                                                            level=1)
                        continue

                    # Read risk and concentration data
                    risk_data = self.read_plt_file(risk_plt_path)
                    conc_data = self.read_plt_file(conc_plt_path)
                    self.iface.messageBar().pushMessage("Debug",
                                                        f"Read {len(risk_data)} risk points and {len(conc_data)} "
                                                        f"concentration points for {group}/{site_type}/{risk_type}",
                                                        level=0)
                    if not risk_data or not conc_data:
                        continue

                    # Collect risk and concentration by istat_COMU
                    area_stats = {}
                    for area_name, info in areas.items():
                        risks, concs = [], []
                        for (x, y, r) in risk_data:
                            point = QgsPointXY(x, y)
                            transformed_point = transform.transform(point)
                            point_geom = QgsGeometry.fromPointXY(transformed_point)
                            # Check if point lands in any polygon of this istat_COMU
                            for geom in info['geometries']:
                                if geom.contains(point_geom):
                                    risks.append(float(r))
                                    # Match concentration
                                    for (cx, cy, c) in conc_data:
                                        conc_point = transform.transform(QgsPointXY(cx, cy))
                                        if abs(transformed_point.x() - conc_point.x()) < 0.00001 and abs(
                                                transformed_point.y() - conc_point.y()) < 0.00001:
                                            concs.append(float(c))
                                            break
                                    break  # Stop checking other geometries once a match is found
                        if risks:  # Include area if at least one point lands in any of its polygons
                            area_stats[area_name] = {
                                'population': info['population'],  # Total population from all polygons
                                'avg_risk': sum(risks) / len(risks),
                                'avg_conc': sum(concs) / len(concs) if concs else 0
                            }
                    self.iface.messageBar().pushMessage("Debug",
                                                        f"Found {len(area_stats)} areas"
                                                        f" with data for {group}/{site_type}/{risk_type}",
                                                        level=0)

                    # Write output file
                    output_path = os.path.join(risk_path, f"POP_RISK_{site_type}_{risk_type}_{group}.txt")
                    with open(output_path, "w") as f:
                        f.write("CAIRO © ~ Population Risk Assessment © 2025\n")
                        f.write(f"Group {group} processed for {site_type} Inhalation Risk, Risk Type: {risk_type}\n")
                        f.write(f"Area Attribute: {area_attr}, Population Attribute: {pop_attr},"
                                f" Pollutant: {self.selected_pollutant}\n\n")
                        conc_label = "C(1H)" if risk_type == "ACUTE" else f"C"
                        header = "{:>20}, {:>12}, {:>13}, {:>13}\n".format("AREA", "POPULATION",
                                                                           risk_type, conc_label)
                        f.write(header)
                        for area_name, stats in sorted(area_stats.items()):
                            risk_value = stats['avg_risk']
                            # Add "H" prefix based on risk type and threshold
                            if risk_type == "R" and risk_value > 0.000001:
                                risk_str = f"H{risk_value:12.9f}"
                            elif risk_type in ["ACUTE", "HI"] and risk_value > 1:
                                risk_str = f"H{risk_value:12.5f}"
                            else:
                                risk_str = f"{risk_value:13.9f}" if risk_type == "R" else f"{risk_value:13.5f}"
                            f.write("{:>20}, {:>12.0f}, {:>13}, {:>13.5f}\n".format(
                                area_name[:20], stats['population'], risk_str, stats['avg_conc']
                            ))

        self.iface.messageBar().pushMessage("Info", "Population risk assessment complete!", level=0)
        QMessageBox.information(self, "Population Risk", "Assessment Complete!")

        self.create_population_summary_file(self.project_folder, groups, self.outdoor_vapor_checkbox.isChecked(),
                                            self.indoor_vapor_checkbox.isChecked())

    def create_population_summary_file(self, project_folder, groups, outdoor_checked, indoor_checked):
        summary_path = os.path.join(project_folder, "RISK", "POP_RISK_SUMMARY.txt")
        with open(summary_path, "w") as f:
            # Header
            area_attr = self.area_attribute_combo.currentText()
            pop_attr = self.population_attribute_combo.currentText()
            f.write("CAIRO © ~ Quantitative Population Risk Assessment © 2025\n")
            f.write(f"Area Attribute: {area_attr}, Population Attribute: {pop_attr},"
                    f"Averaged risk and concentration values over areas for {self.selected_pollutant}\n\n")

            for group in groups:
                f.write(f"{group}\n\n")
                site_types = []
                if outdoor_checked:
                    site_types.append(("outdoor", "Outdoor inhalation"))
                if indoor_checked:
                    site_types.append(("indoor", "Indoor inhalation"))

                for site_type, site_title in site_types:
                    f.write(f"{site_title}\n")
                    # Paths to POP_RISK_*.txt files
                    risk_path = os.path.join(project_folder, "RISK", f"risk_{group}", site_type)
                    acute_file = os.path.join(risk_path, "ACUTE", f"POP_RISK_{site_type}_ACUTE_{group}.txt")
                    hi_file = os.path.join(risk_path, "HI", f"POP_RISK_{site_type}_HI_{group}.txt")
                    r_file = os.path.join(risk_path, "R", f"POP_RISK_{site_type}_R_{group}.txt")

                    # Check availability
                    has_acute = os.path.exists(acute_file)
                    has_hi = os.path.exists(hi_file)
                    has_r = os.path.exists(r_file)
                    chronic_period = "chronic"

                    # Collect data
                    data = {}
                    if has_acute:
                        with open(acute_file, "r") as af:
                            lines = af.readlines()[5:]  # Skip header (4 lines)
                            for line in lines:
                                parts = line.split(",")
                                if len(parts) >= 4:
                                    area = parts[0]
                                    data[area] = data.get(area, {})
                                    data[area]["POPULATION"] = float(parts[1])
                                    data[area]["ACUTE"] = parts[2]
                                    data[area]["C(1H)"] = float(parts[3])
                    if has_hi:
                        with open(hi_file, "r") as hf:
                            lines = hf.readlines()[5:]
                            for line in lines:
                                parts = line.split(",")
                                if len(parts) >= 4:
                                    area = parts[0]
                                    data[area] = data.get(area, {})
                                    data[area]["POPULATION"] = float(parts[1])
                                    data[area]["HI"] = parts[2]
                                    data[area][f"C({chronic_period})"] = float(parts[3])
                    if has_r:
                        with open(r_file, "r") as rf:
                            lines = rf.readlines()[5:]
                            for line in lines:
                                parts = line.split(",")
                                if len(parts) >= 4:
                                    area = parts[0]
                                    data[area] = data.get(area, {})
                                    data[area]["POPULATION"] = float(parts[1])
                                    data[area]["R"] = parts[2]
                                    if "C(ANNUAL)" not in data[area] and "C(PERIOD)" not in data[area]:
                                        data[area][f"C({chronic_period})"] = float(parts[3])

                    columns = ["AREA", "POPULATION"]
                    if has_acute:
                        columns.extend(["ACUTE", "C(1H)"])
                    if has_hi:
                        columns.append("HI")
                    if has_r:
                        columns.append("R")
                    if has_hi or has_r:
                        columns.append(f"C({chronic_period})")
                    widths = {
                        "AREA": 20,
                        "POPULATION": 12,
                        "R": 13,
                        "HI": 13,
                        "ACUTE": 13,
                        "C(1H)": 13,
                        f"C({chronic_period})": 13
                    }

                    header = " ".join(f"{col:>{widths[col]}}" for col in columns) + "\n"
                    f.write(header)

                    for area, values in sorted(data.items(), key=lambda x: x[1]["POPULATION"], reverse=True):
                        row = [
                            f"{area[:widths['AREA']]:>{widths['AREA']}}",
                            f"{values.get('POPULATION', 0):>{widths['POPULATION']}.0f}"
                        ]
                        for col in columns[2:]:
                            value = values.get(col, "N/A")
                            if col in ["R", "HI", "ACUTE"] and isinstance(value, str) and value.startswith("H"):
                                row.append(f"{value:>{widths[col]}}")
                            else:
                                try:
                                    num_value = float(value)
                                    row.append(f"{num_value:>{widths[col]}.5f}")
                                except (ValueError, TypeError):
                                    row.append(f"{value:>{widths[col]}}")
                        f.write(" ".join(row) + "\n")
                    f.write("\n")

        os.startfile(summary_path)

    def read_plt_file(self, plt_path):
        data = []
        try:
            with open(plt_path, "r") as f:
                lines = f.readlines()
            for line in lines:
                if line.strip().startswith('*'):
                    continue
                fields = line.strip().split()
                expected_fields = 11 if "ACUTE" in plt_path else 10
                if len(fields) != expected_fields:
                    continue
                try:
                    x, y, value = float(fields[0]), float(fields[1]), float(fields[2])
                    data.append((x, y, value))
                except ValueError:
                    continue
            return data
        except Exception as e:
            self.iface.messageBar().pushMessage("Warning", f"Error reading {plt_path}: {str(e)}", level=1)
            return []

    def process_fwd_subfolder(self, fwd_path, aerplot_path, group, site_type, risk_type,
                              selected_receptors, arfc, iur, rfc, coordinates, utm_zone, hemisphere, avg_period):
        if risk_type == "ACUTE":
            plt_file = f"PLOT1H_{group}.plt"
        else:
            plt_file = f"PLOT{avg_period}_{group}.plt"
        src_plt_path = os.path.join(aerplot_path, plt_file)
        if not os.path.exists(src_plt_path):
            self.iface.messageBar().pushMessage("Warning", f"{plt_file} not found in {aerplot_path}", level=1)
            return

        for file_name in ["aermod.inp", "aermod.out", plt_file]:
            shutil.copy(os.path.join(aerplot_path, file_name), fwd_path)
        shutil.copy(os.path.join(self.plugin_dir, "aerplot.exe"), fwd_path)

        plt_path = os.path.join(fwd_path, plt_file)
        with open(plt_path, 'r') as f:
            lines = f.readlines()

        data_start = 0
        for i, line in enumerate(lines):
            fields = line.strip().split()
            if len(fields) == 11:
                data_start = i
                break
        if data_start == 0:
            self.iface.messageBar().pushMessage("Error", f"No data lines in {plt_file}", level=2)
            return

        max_concentration = 0.0
        max_conc_coords = (0.0, 0.0)
        max_conc_risk = 0.0
        modified_lines = []
        risk_nodes = []
        C_acc = float('inf')

        for line in lines:
            if line.strip().startswith('*'):
                modified_lines.append(line)
                continue

            fields = line.strip().split()
            expected_fields = 11 if risk_type == "ACUTE" else 10
            if len(fields) != expected_fields:
                continue

            try:
                X = float(fields[0])
                Y = float(fields[1])
                C = float(fields[2])
            except ValueError as e:
                self.iface.messageBar().pushMessage(
                    "Warning",
                    f"Skipping line with invalid data: {line.strip()}",
                    level=1
                )
                continue

            EC_list = []
            for receptor in selected_receptors:
                factors = self.get_exposure_factors(receptor)
                denominator = factors['BW'] * factors['AT'] * 365 if risk_type == "R" else factors['BW'] * factors[
                    'ED'] * 365
                if site_type == "outdoor":
                    EC = (factors['Bo'] * factors['EFgo'] * factors['EF'] * factors['ED']) / denominator
                else:  # indoor
                    EC = (factors['Bi'] * factors['EFgi'] * factors['EF'] * factors['ED']) / denominator
                EC_list.append(EC)

            if len(selected_receptors) > 1:
                if self.critical_receptor_checkbox.isChecked():
                    EC_used = max(EC_list)
                else:
                    EC_used = sum(EC_list) / len(EC_list)
            else:
                EC_used = EC_list[0]

            if risk_type == "R":
                C_acc = 0.000001 / (float(iur) * EC_used) if float(iur) * EC_used != 0 else float('inf')
            elif risk_type == "HI":
                C_acc = 1 / (EC_used / float(rfc)) if EC_used / float(rfc) != 0 else float('inf')
            else:
                C_acc = 1 / (EC_used / float(arfc)) if EC_used / float(arfc) != 0 else float('inf')

            if risk_type == "R":
                risk = C * float(iur) * EC_used
            elif risk_type == "HI":
                risk = C * (EC_used / float(rfc))
            else:
                risk = C * (EC_used / float(arfc))

            if C > max_concentration:
                max_concentration = C
                max_conc_coords = (X, Y)
                max_conc_risk = risk

            if risk_type == "ACUTE":
                new_line = (f" {X:13.5f} {Y:13.5f} {risk:13.5f}   {float(fields[3]):8.2f}   {float(fields[4]):8.2f}"
                            f"   {float(fields[5]):8.2f}   {fields[6]:5s}  {fields[7]:8s}  {fields[8]:5s}"
                            f"     {fields[9]:8s}  {int(fields[10]):8d}")
            else:  # R or HQ
                risk_precision = 13.9 if risk_type == "R" else 13.5
                new_line = (
                    f" {X:13.5f} {Y:13.5f} {risk:{risk_precision}f}   {float(fields[3]):8.2f}   {float(fields[4]):8.2f}"
                    f"   {float(fields[5]):8.2f}   {fields[6]:6s}  {fields[7]:8s}  {int(fields[8]):8d}"
                    f"     {fields[9]:8s}")

            modified_lines.append(new_line + "\n")

            for easting, northing in coordinates:
                if abs(X - easting) < 1 and abs(Y - northing) < 1:
                    risk_nodes.append((easting, northing, risk, C))

        ind_out = "OUT" if site_type == "outdoor" else "IND"
        if risk_type == "ACUTE":
            file_avg_period = "1H"
        else:
            file_avg_period = avg_period

        new_plt_name = f"RISK_{ind_out}_{risk_type}_{group}_{file_avg_period}.plt"
        new_plt_path = os.path.join(fwd_path, new_plt_name)
        with open(new_plt_path, "w") as f:
            f.writelines(modified_lines)

            risknodes_name = f"RISK_REC_{ind_out}_{risk_type}_{group}.txt"
            risknodes_path = os.path.join(fwd_path, risknodes_name)
            with open(risknodes_path, "w") as f:
                selected_receptor = self.receptor_combobox.currentText()

                critical_receptor_state = "true" if self.critical_receptor_checkbox.isChecked() else "false"

                f.write("CAIRO © ~ Air Risk Assessment Module © 2025.\n")
                inhalation_type = "Indoor vapor inhalation" if ind_out == "IND" else "Outdoor vapor inhalation"
                risk_type_text = "Carcinogenic Risk" if risk_type == "R" else "Toxicological Risk"
                f.write(
                    f"Risk Assessment at specific receptors for {inhalation_type} {risk_type_text}\n"
                    f"{group} proccessed at averaging period: {file_avg_period}\n"
                    f"Receptor: {selected_receptor}; Most Critical Receptor = {critical_receptor_state}\n"
                    f"Pollutant: {self.selected_pollutant}\n"
                    f"Acceptable Concentration: C({risk_type_text}) < {C_acc:.5f}\n"
                )
                f.write("\n")
                risk_type_text = "R" if risk_type == "R" else ("HI" if risk_type == "HI" else "ACUTE")
                conc_label = "C(1H)" if risk_type == "ACUTE" else f"C({file_avg_period})"
                header = "{:>15}, {:>20}, {:>20}, {:>15}, {:>15}".format(
                    "Receptor Name", "Easting", "Northing", risk_type_text, conc_label
                )
                f.write(f"{header}\n")
                max_risk_str = f"{max_conc_risk:13.9f}" if risk_type == "R" else f"{max_conc_risk:13.5f}"
                if risk_type == "R" and max_conc_risk > 0.000001:
                    max_risk_str = f"H{max_conc_risk:12.9f}"
                elif risk_type in ["ACUTE", "HI"] and max_conc_risk > 1:
                    max_risk_str = f"H{max_conc_risk:12.5f}"
                f.write(
                    "{:>15}, {:>20}, {:>20}, {:>15}, {:>15}\n".format(
                        "MAXIMUM",
                        f"{max_conc_coords[0]:13.5f}",
                        f"{max_conc_coords[1]:13.5f}",
                        max_risk_str, f"{max_concentration:13.5f}"
                    )
                )
                for easting, northing, risk, C in risk_nodes:
                    receptor_name = "Unknown"
                    for row in range(self.coordinates_table.rowCount()):
                        easting_item = self.coordinates_table.item(row, 0)
                        northing_item = self.coordinates_table.item(row, 1)
                        receptor_item = self.coordinates_table.item(row, 2)
                        if easting_item and northing_item:
                            try:
                                table_easting = float(easting_item.text())
                                table_northing = float(northing_item.text())
                                if abs(table_easting - easting) < 1 and abs(
                                        table_northing - northing) < 1:
                                    receptor_name = receptor_item.text() if receptor_item else f"Receptor_{row + 1}"
                                    break
                            except ValueError:
                                continue
                    risk_str_txt = f"{risk:13.8f}" if risk_type == "R" else f"{risk:13.5f}"
                    if risk_type == "R" and risk > 0.000001:
                        risk_str_txt = f"H{risk:12.8f}"
                    elif risk_type in ["ACUTE", "HI"] and risk > 1:
                        risk_str_txt = f"H{risk:12.5f}"
                    f.write(
                        "{:>15}, {:>20}, {:>20}, {:>15}, {:>15}\n".format(
                            receptor_name,
                            f"{easting:13.5f}",
                            f"{northing:13.5f}",
                            risk_str_txt, f"{C:13.5f}"
                        )
                    )

        base_name = new_plt_name.replace(".plt", "")
        min_bin = self.minimum_bin_textbox.text()
        max_bin = self.maximum_bin_textbox.text()
        custom_bin = self.custom_bins_textbox.text()
        aerplot_inp_content = f"""
    version=2
    origin=UTM
    easting=0
    northing=0
    utmZone={utm_zone}
    {hemisphere}=true
    originLatitude=0
    originLongitude=0
    altitudeChoice=relativeToGround
    altitude=0
    PlotFileName={new_plt_name}
    SourceDisplayInputFileName=aermod.inp
    OutputFileNameBase={base_name}
    NameDisplayedInGoogleEarth={base_name}
    sDisableProgressMeter=false
    sDisableEarthBrowser=true
    IconScale=0.40
    sIconSetChoice=redGreen
    minbin={min_bin}
    maxbin={max_bin}
    binningChoice=Linear
    customBinningElevenLevels={custom_bin}
    contourLegendTitleHTML=RISK ASSESSMENT
    numberOfGridCols=400
    numberOfGridRows=400
    numberOfTimesToSmoothContourSurface=1
    makeContours=true
    contourExtension=9999999
    makeGradients=true
    gradientExtension=9999999
    gradientMaxBin=data
    gradientMinBin=data
    gradientBinningChoice=Linear
    customGradBinElevenLevels=na
    gradientLegendTitleHTML=Gradient Magnitudes
    provideEvenlySpacedInterpolatedGrid=false
        """
        aerplot_inp_content = textwrap.dedent(aerplot_inp_content).strip()
        with open(os.path.join(fwd_path, "aerplot.inp"), "w") as f:
            f.write(aerplot_inp_content)

        process = QProcess(self)
        process.setWorkingDirectory(fwd_path)
        process.start(os.path.join(fwd_path, "aerplot.exe"))
        self.process_manager.add_process(process, fwd_path)

    def create_summary_file(self, project_folder, groups, outdoor_checked, indoor_checked, avg_periods):
        summary_path = os.path.join(project_folder, "RISK", "RISK_SUMMARY.txt")
        with open(summary_path, "w") as f:
            database_path = os.path.join(self.plugin_dir, "database.csv")
            with open(database_path, 'r') as csvfile:
                reader = csv.reader(csvfile, delimiter=';')
                rows = list(reader)
                for row in rows[1:]:
                    if row[1] == self.selected_pollutant:
                        arfc = row[3]
                        iur = row[2]
                        rfc = row[4]
                        break
                else:
                    self.iface.messageBar().pushMessage("Error", "Pollutant not found in database.csv", level=2)
                    return

            receptor_groups = {
                0: [0, 2],  # Adults and Children
                1: [0, 1, 2, 3],  # All
                2: [2],  # Adults
                3: [4]  # Workers
            }
            selected_receptors = receptor_groups[self.receptor_combobox.currentIndex()]

            EC_used = {}
            for risk_type in ["R", "HI", "ACUTE"]:
                EC_list = []
                for receptor in selected_receptors:
                    factors = self.get_exposure_factors(receptor)
                    denominator = factors['BW'] * factors['AT'] * 365 if risk_type == "R" else factors['BW'] * factors[
                        'ED'] * 365
                    EC = (factors['Bo'] * factors['EFgo'] * factors['EF'] * factors[
                        'ED']) / denominator  # Outdoor default
                    EC_list.append(EC)
                if len(selected_receptors) > 1:
                    EC_used[risk_type] = max(EC_list) if self.critical_receptor_checkbox.isChecked() else sum(
                        EC_list) / len(EC_list)
                else:
                    EC_used[risk_type] = EC_list[0]

            C_acc = {}
            if iur != '' and iur != '0':
                C_acc["R"] = 0.000001 / (float(iur) * EC_used["R"]) if float(iur) * EC_used["R"] != 0 else float('inf')
            if rfc != '' and rfc != '0':
                C_acc["HI"] = 1 / (EC_used["HI"] / float(rfc)) if EC_used["HI"] / float(rfc) != 0 else float('inf')
            if arfc != '' and arfc != '0':
                C_acc["ACUTE"] = 1 / (EC_used["ACUTE"] / float(arfc)) if EC_used["ACUTE"] / float(arfc) != 0 else float(
                    'inf')

            selected_receptor = self.receptor_combobox.currentText()
            critical_receptor_state = "true" if self.critical_receptor_checkbox.isChecked() else "false"
            f.write("CAIRO © ~ Air Risk Assessment Module © 2025.\n")
            f.write("Risk Assessment at specific receptors Summary Table\n")
            f.write(f"Receptor: {selected_receptor}; Most Critical Receptor = {critical_receptor_state}\n\n")
            f.write(f"Pollutant: {self.selected_pollutant}\n")
            acc_lines = []
            for risk_type, value in C_acc.items():
                acc_lines.append(f"Acceptable Concentration: C({risk_type}) < {value:.5f}")
            if acc_lines:
                f.write("\n".join(acc_lines) + "\n")
            f.write("\n")

            for group in groups:
                periods = []
                if "1H" in avg_periods[group]:
                    periods.append("1H")
                if "ANNUAL" in avg_periods[group]:
                    periods.append("ANNUAL")
                elif "PERIOD" in avg_periods[group]:
                    periods.append("PERIOD")

                f.write(f"  {group}\n\n")

                site_types = []
                if outdoor_checked:
                    site_types.append(("outdoor", "Outdoor Inhalation Risk"))
                if indoor_checked:
                    site_types.append(("indoor", "Indoor Inhalation Risk"))

                for site_type, site_title in site_types:
                    f.write(f"{site_title}\n")

                    risk_path = os.path.join(project_folder, "RISK", f"risk_{group}", site_type)
                    acute_file = os.path.join(risk_path, "ACUTE",
                                              f"RISK_REC_{'OUT' if site_type == 'outdoor' else 'IND'}_ACUTE_{group}.txt")
                    hi_file = os.path.join(risk_path, "HI",
                                           f"RISK_REC_{'OUT' if site_type == 'outdoor' else 'IND'}_HI_{group}.txt")
                    r_file = os.path.join(risk_path, "R",
                                          f"RISK_REC_{'OUT' if site_type == 'outdoor' else 'IND'}_R_{group}.txt")

                    has_acute = os.path.exists(acute_file)
                    has_hi = os.path.exists(hi_file)
                    has_r = os.path.exists(r_file)
                    chronic_period = avg_periods[group].get("chronic", "PERIOD")

                    data = {}
                    if has_acute:
                        with open(acute_file, "r") as af:
                            lines = af.readlines()[5:]
                            for line in lines:
                                parts = [p.strip() for p in line.split(",")]
                                if len(parts) == 5:
                                    key = (parts[0], parts[1], parts[2])
                                    data[key] = data.get(key, {})
                                    data[key]["ACUTE"] = parts[3]
                                    data[key]["C(1H)"] = parts[4]
                    if has_hi:
                        with open(hi_file, "r") as hf:
                            lines = hf.readlines()[5:]
                            for line in lines:
                                parts = [p.strip() for p in line.split(",")]
                                if len(parts) == 5:
                                    key = (parts[0], parts[1], parts[2])
                                    data[key] = data.get(key, {})
                                    data[key]["HI"] = parts[3]
                                    data[key][f"C({chronic_period})"] = parts[4]
                    if has_r and not has_hi:
                        with open(r_file, "r") as rf:
                            lines = rf.readlines()[5:]
                            for line in lines:
                                parts = [p.strip() for p in line.split(",")]
                                if len(parts) == 5:
                                    key = (parts[0], parts[1], parts[2])
                                    data[key] = data.get(key, {})
                                    data[key]["R"] = parts[3]
                                    data[key][f"C({chronic_period})"] = parts[4]
                    elif has_r:
                        with open(r_file, "r") as rf:
                            lines = rf.readlines()[5:]
                            for line in lines:
                                parts = [p.strip() for p in line.split(",")]
                                if len(parts) == 5:
                                    key = (parts[0], parts[1], parts[2])
                                    data[key] = data.get(key, {})
                                    data[key]["R"] = parts[3]

                    columns = ["Receptor Name", "Easting", "Northing"]
                    if has_acute:
                        columns.extend(["ACUTE", "C(1H)"])
                    if has_hi:
                        columns.append("HI")
                    if has_r:
                        columns.append("R")
                    if has_hi or has_r:
                        columns.append(f"C({chronic_period})")
                    header = ", ".join(f"{col:>20}" for col in columns)
                    f.write(f"  {header}\n")

                    for (name, easting, northing), values in data.items():
                        row = [f"{name:>20}", f"{easting:>20}", f"{northing:>20}"]
                        for col in columns[3:]:
                            value = values.get(col, "N/A")
                            row.append(f"{value:>20}")
                        f.write(f"  {', '.join(row)}\n")
                    f.write("\n")
        with open(summary_path, "r") as f:
            lines = f.readlines()

        cleaned_lines = []
        in_table = False
        header_count = 0
        prev_line_was_header = False

        for line in lines:
            stripped_line = line.strip()
            if stripped_line in ["Outdoor Inhalation Risk", "Indoor Inhalation Risk"]:
                in_table = True
                header_count = 0
                cleaned_lines.append(line)
                continue
            if in_table and "Receptor Name" in stripped_line and "Easting" in stripped_line and "Northing" in stripped_line:
                header_count += 1
                if header_count == 1:
                    cleaned_lines.append(line)
                    prev_line_was_header = True
                continue
            if in_table and not stripped_line:
                in_table = False
                cleaned_lines.append(line)
                continue
            if not prev_line_was_header or header_count > 1:
                cleaned_lines.append(line)
            prev_line_was_header = False

        with open(summary_path, "w") as f:
            f.writelines(cleaned_lines)

        os.startfile(summary_path)

    def get_exposure_factors(self, receptor_idx):
        col = 3 + receptor_idx

        def get_float(row, col, default=0.0):
            item = self.exposure_table.item(row, col)
            return float(item.text()) if item and item.text().strip() else default

        BW = get_float(1, col)  # Row 1: Body Weight
        AT = get_float(2, col)  # Row 2: Averaging Time
        ED = get_float(3, col)  # Row 3: Exposure Duration
        EF = get_float(4, col)  # Row 4: Exposure Frequency
        EFgo = get_float(6, col)  # Row 6: Outdoor Daily Frequency
        Bo = get_float(7, col)  # Row 7: Outdoor Vapor Inhalation Rate
        EFgi = get_float(9, col)  # Row 10: Indoor Daily Frequency
        Bi = get_float(10, col)  # Row 11: Indoor Vapor Inhalation Rate

        return {"BW": BW, "AT": AT, "ED": ED, "EF": EF, "EFgo": EFgo, "Bo": Bo, "EFgi": EFgi, "Bi": Bi}


class CAIRODialog(QDialog):
    def __init__(self, parent=None):
        super(CAIRODialog, self).__init__(parent)
        self.original_working_dir = os.getcwd()
        self.active_processes = []
        self.plugin_dir = os.path.dirname(__file__)
        self.input_folder = None

        self.aermap_window = None
        self.aermod_window = None
        self.aerplot_window = None

        self.stage_labels = ["AERMAP", "AERMOD", "AERPLOT"]
        self.status_labels = []

        self.initUI()

    def initUI(self):
        self.setWindowTitle("CAIRO © ~ Compile AERMOD Input and Risk Omniware")

        layout = QVBoxLayout()

        top_layout = QHBoxLayout()

        image_label = QLabel()
        image_path = os.path.join(self.plugin_dir, "CAIRO.png")
        if os.path.exists(image_path):
            pixmap = QPixmap(image_path)
            image_label.setPixmap(pixmap)
            image_label.setAlignment(Qt.AlignLeft | Qt.AlignTop)
        else:
            image_label.setText("Image not found: CAIRO.png")
        top_layout.addWidget(image_label)

        title_vbox = QVBoxLayout()
        title_label = QLabel("CAIRO © for AERMOD v3.0")
        title_label.setFont(QFont('Arial', 14, QFont.Bold))
        title_label.setAlignment(Qt.AlignCenter)
        title_vbox.addWidget(title_label)

        subtitle_label = QLabel("CAIRO © ~ Compile AERMOD Input and Risk Omniware")
        subtitle_label.setFont(QFont('Arial', 8))
        subtitle_label.setAlignment(Qt.AlignCenter)
        title_vbox.addWidget(subtitle_label)

        top_layout.addLayout(title_vbox)
        top_layout.addStretch()
        layout.addLayout(top_layout)

        main_layout = QHBoxLayout()

        # Input Layout (Generator Buttons)
        main_layout.addStretch(1)  # Add stretch before to balance the midline
        input_layout = QVBoxLayout()
        input_labels = ["AERMAP Input Generator", "AERMOD Input Generator", "AERPLOT Input Generator"]
        input_actions = [self.open_aermap, self.open_aermod, self.open_aerplot]
        for i, (label, action) in enumerate(zip(input_labels, input_actions)):
            button = QPushButton(label)
            button.setFont(QFont('Arial', 10))
            button.clicked.connect(action)
            if i == 0:
                button.setToolTip(
                    "Create AERMAP input file;\nLive Domain Visualisation;\nMap "
                    "Coordinate to Input;\nAutomatic File and Folder Management")
            elif i == 1:
                button.setToolTip(
                    "Create AERMOD input file;\nLive Source Visualisation;\nMap "
                    "Coordinates to input;\nAutomatic File and Folder Management")
            elif i == 2:
                button.setToolTip(
                    "Create AERPLOT input file;\nMultiple Plotfiles "
                    "Processed Simultaneously;\nAutomatic File and Folder Management")
            input_layout.addWidget(button)
            if i < 2:  # Add spacer between buttons
                spacer_label = QLabel("")
                spacer_label.setFixedHeight(10)
                input_layout.addWidget(spacer_label)
        main_layout.addLayout(input_layout)

        # Run Layout (Run Buttons and Status)
        run_button_layout = QVBoxLayout()
        run_status_layout = QVBoxLayout()
        for i, label in enumerate(self.stage_labels):
            button = QPushButton(label)
            button.setFont(QFont('Arial', 10))
            button.clicked.connect(lambda checked, idx=i: self.run_stage(idx))
            if i == 0:
                button.setToolTip("Run AERMAP preprocessor;\nSelect Project Folder;\nData is automatically fetched")
            elif i == 1:
                button.setToolTip("Run AERMOD processor;\nSelect Project Folder;\nData is automatically fetched")
            elif i == 2:
                button.setToolTip(
                    "Run AERPLOT postprocessor;\nSelect Project Folder;\nMultiple "
                    "Plotfiles Processed Simultaneously;\nData is automatically fetched")
            run_button_layout.addWidget(button)
            if i < 2:  # Add spacer to match input layout
                spacer_label = QLabel("")
                spacer_label.setFixedHeight(10)
                run_button_layout.addWidget(spacer_label)

            status_label = QLabel("")
            status_label.setFont(QFont('Arial', 12))
            status_label.setAlignment(Qt.AlignCenter)
            status_label.setFixedWidth(40)  # Narrow status column
            self.status_labels.append(status_label)
            run_status_layout.addWidget(status_label)

        run_layout = QHBoxLayout()
        run_layout.addLayout(run_button_layout)
        run_layout.addLayout(run_status_layout)
        main_layout.addLayout(run_layout)
        main_layout.addStretch(1)  # Add stretch after to balance the midline

        layout.addLayout(main_layout)
        # Add an empty row (spacer) above the extra buttons
        spacer_label = QLabel("")
        spacer_label.setFixedHeight(20)  # Adjust height as needed for spacing
        layout.addWidget(spacer_label)

        extra_buttons_layout = QHBoxLayout()

        risk_analysis_button = QPushButton("Risk Assessment")
        risk_analysis_button.setFont(QFont('Arial', 10))
        risk_analysis_button.clicked.connect(self.run_risk_analysis)
        risk_analysis_button.setToolTip("Perform risk assessment")
        extra_buttons_layout.addWidget(risk_analysis_button)

        buy_meteo_data_button = QPushButton("Buy Meteo Data")
        buy_meteo_data_button.setFont(QFont('Arial', 10))
        buy_meteo_data_button.clicked.connect(self.buy_meteo_data)
        buy_meteo_data_button.setToolTip("Purchase meteorological data (placeholder)")
        extra_buttons_layout.addWidget(buy_meteo_data_button)

        layout.addLayout(extra_buttons_layout)

        bottom_layout = QHBoxLayout()
        footer_label = QLabel("© MSc Dominik Subotić, 2025\nContact: suboticdominik@gmail.com")
        footer_label.setFont(QFont('Arial', 8))
        footer_label.setAlignment(Qt.AlignCenter)
        bottom_layout.addWidget(footer_label)

        info_button = QPushButton("ℹ Info")
        info_button.setFont(QFont('Arial', 10))
        info_button.clicked.connect(self.show_info)
        info_button.setToolTip("Show information about CAIRO ©")
        bottom_layout.addWidget(info_button, alignment=Qt.AlignRight)

        layout.addLayout(bottom_layout)

        layout.addStretch()
        self.setLayout(layout)

    def show_info(self):
        info_dialog = InfoDialog(self)
        info_dialog.exec_()

    def open_aermap(self):
        dialog = ReceptorGridDialog(self)
        dialog.exec_()

    def open_aermod(self):
        dialog = SourceTypeDialog(self)
        dialog.exec_()

    def open_aerplot(self):
        dialog = GroupDialog(self)
        dialog.exec_()

    def run_stage(self, stage_index):
        input_folder = QFileDialog.getExistingDirectory(self, "Select Input Folder")
        if input_folder:
            original_dir = os.getcwd()
            try:
                os.chdir(input_folder)
                self.input_folder = input_folder

                executable = os.path.join(self.plugin_dir, f"{self.stage_labels[stage_index].lower()}.exe")

                if not os.path.exists(executable):
                    iface.messageBar().pushMessage(
                        "Error", f"{self.stage_labels[stage_index]}.exe not found in plugin directory.",
                        level=2
                    )
                    return

                loading_movie = QMovie(os.path.join(self.plugin_dir, "loading.gif"))
                self.status_labels[stage_index].setMovie(loading_movie)
                self.status_labels[stage_index].setAlignment(Qt.AlignTop)
                loading_movie.start()

                if self.stage_labels[stage_index] == "AERPLOT":
                    aerplot_folders = [f for f in os.listdir(input_folder) if
                                       os.path.isdir(os.path.join(input_folder, f)) and f.startswith("aerplot")]
                    for aerplot_folder in aerplot_folders:
                        try:
                            folder_path = os.path.join(input_folder, aerplot_folder)
                            os.chdir(folder_path)
                            copied_exe_path = os.path.join(folder_path, "aerplot.exe")
                            shutil.copy(executable, copied_exe_path)
                            time.sleep(5)
                            process = QProcess(self)
                            self.active_processes.append((process, folder_path))
                            process.setProgram(copied_exe_path)
                            process.setProcessChannelMode(QProcess.MergedChannels)
                            process.finished.connect(
                                lambda exit_code, exit_status, idx=stage_index: self.on_process_finished(
                                    exit_code, exit_status, idx))
                            process.start()
                        except Exception as e:
                            print(f"Error launching AERPLOT in {aerplot_folder}: {str(e)}")
                        finally:
                            os.chdir(input_folder)
                else:
                    try:
                        process = QProcess(self)
                        self.active_processes.append((process, None))
                        process.setProgram(executable)
                        process.setProcessChannelMode(QProcess.MergedChannels)
                        process.finished.connect(
                            lambda exit_code, exit_status, idx=stage_index: self.on_process_finished(
                                exit_code, exit_status, idx))
                        process.start()
                    except Exception as e:
                        print(f"Error launching {self.stage_labels[stage_index]}: {str(e)}")
            finally:
                os.chdir(original_dir)

    def on_process_finished(self, exit_code, exit_status, index):
        sender_process = self.sender()
        folder_path = None
        for i, (process, path) in enumerate(self.active_processes[:]):
            if process == sender_process:
                folder_path = path
                self.active_processes.pop(i)
                break

        current_dir = os.getcwd()
        try:
            os.chdir(self.input_folder)

            plugin_dir = os.path.dirname(os.path.realpath(__file__))
            success_icon_path = os.path.join(plugin_dir, "success.png")

            if exit_code == 0:
                pixmap = QPixmap(success_icon_path)
                if pixmap.isNull():
                    self.status_labels[index].setText("✓")
                    self.status_labels[index].setStyleSheet("color: green; font-size: 24px;")
                else:
                    self.status_labels[index].setPixmap(pixmap)
                    self.status_labels[index].setAlignment(Qt.AlignTop)
                    self.status_labels[index].setStyleSheet("")

                if self.stage_labels[index] in ["AERMAP", "AERMOD"]:
                    output_file = f"{self.stage_labels[index].lower()}.out"
                    output_file_path = os.path.join(self.input_folder, output_file)
                    if os.path.exists(output_file_path):
                        QTimer.singleShot(1000, lambda: self.open_output_file(output_file_path))
            else:
                self.status_labels[index].setText("✗")
                self.status_labels[index].setStyleSheet("color: red; font-size: 24px;")

            if self.stage_labels[index] == "AERPLOT" and folder_path:
                exe_path = os.path.join(folder_path, "aerplot.exe")
                if os.path.exists(exe_path):
                    try:
                        os.remove(exe_path)
                    except Exception as e:
                        print(f"Failed to delete aerplot.exe from {exe_path}: {str(e)}")
        finally:
            os.chdir(current_dir)
            if self.status_labels[index].movie():
                self.status_labels[index].movie().stop()
                self.status_labels[index].setMovie(None)

    def open_output_file(self, file_path):
        QDesktopServices.openUrl(QUrl.fromLocalFile(file_path))

    def run_risk_analysis(self):
        dialog = RiskAssessmentDialog(self.plugin_dir, iface, self)
        dialog.exec_()

    def buy_meteo_data(self):
        iface.messageBar().pushMessage("Info", "Buy Meteo Data functionality not yet implemented.", level=0)

    def closeEvent(self, event):
        for process in self.active_processes:
            if process.state() == QProcess.Running:
                process.terminate()
                process.waitForFinished()

        self.active_processes.clear()

        os.chdir(self.original_working_dir)

        if self.aermap_window:
            self.aermap_window.close()
        if self.aermod_window:
            self.aermod_window.close()
        if self.aerplot_window:
            self.aerplot_window.close()

        event.accept()


class InfoDialog(QDialog):
    def __init__(self, parent=None):
        super(InfoDialog, self).__init__(parent)
        self.setWindowTitle("About CAIRO")
        self.setMinimumSize(800, 600)

        layout = QVBoxLayout()

        info_text = QTextEdit()
        info_text.setReadOnly(True)
        info_text.setText(
            "CAIRO © ~ Compile AERMOD Input and Risk Omniware\n\n"
            "Tutorial: [Link to tutorial video]\n\n"
            "Created by MSc Dominik Subotić in collaboration with Prof. Giorgio Passerini "
            "and PhD Simone Virgili at Università Politecnica delle Marche, Italy, in 2025.\n\n"
            "CAIRO © for AERMOD is a QGIS plugin developed to create and run AERMAP, AERMOD, and AERPLOT input "
            "files and run "
            "forward, backward and population risk analysis, with integrated map input, domain and source "
            "visualization, and automated project folder structure. Its aimed "
            "at streamlining the process of creating complex input files with unique syntax and "
            "running them, eliminating the need to manually write inputs and execute the program "
            "through Windows Shell.\n\n"
            "Order of operations:\n"
            "1. AERMAP Input Generator\n"
            "2. AERMAP\n"
            "3. AERMOD Input Generator\n"
            "4. AERMOD\n"
            "5. AERPLOT Input Generator\n"
            "6. AERPLOT\n"
            "7. Risk Assessment\n"
            "8. Quantitative Population Risk Assessment\n"
            "AERMAP is a terrain preprocessor. AERMOD is a steady-state plume dispersion modeling "
            "software. AERPLOT is a postprocessor for visualizing AERMOD results, developed by EPA."
            "Risk assessment is performed by applying backward and forward risk models to AERPLOT output, with tabular "
            "and map output, based on the \"Consolidated Table of "
            "OEHHA/ARB Approved Risk Assessment Health Values\".\n\n"
            "AERMAP features:\n - Rectangular, Polar and Discrete receptor grid\n - Map input of Anchor/Center/Receptor"
            "\n - Live Domain visualization\n - Automatic file fetching, copying and project folder structure\n"
            "\nAERMOD features:\n - Urban areas and sources\n - Point, Line, AreaPolygon and Volume sources\n"
            " - ALL keyword for group sources to include all sources\n"
            " - ALLRURAL keyword for group sources to include all normal (non-urban) sources\n"
            " - ALLURBAN keyword for group sources to include all urban sources\n"
            " - Map input and live visualization of sources, along with attribute table including source metadata\n"
            " - Rectable, Maxtable, Rankfile, Maxifile, Plotfile outputs\n"
            " - Automatic file fetching, copying and project folder structure\n"
            "\nAEPLOT features:\n - Instantaneous Multiple plot input file creation and processing\n"
            " - Creates subfolder for every plotfile (Input file generator) and runs all kmz"
            " conversions at once (AERPLOT)\n\n"
            "Risk assessment features:\n"
            " - Backward and forward model\n"
            " - Population Risk Assessment based on GEOSTAT data and region averaged AERMOD output\n"
            " - Acute non-cancer risk (ACUTE) and chronic cancer (R) and non-cancer risk (HI)\n"
            " - Outdoor and Indoor vapor inhalation risk\n"
            " - Most Critical Receptor\n"
            " - Editable specific exposure parameters table\n"
            " - Leverages AERPLOT for risk map creation and relies on the created folder structure\n"
            " - Requires running AERPLOT postprocessing on 1h (for acute risk) and ANNUAL or PERIOD (for R and HI) "
            "averaging periods using CAIRO, due to the specific project folder structure\n"
            "Quantitative Population Risk Assessment averages the risk and concentration over the user selected area "
            "level and outputs a list of areas, their population, average concentration and risk.\n"
            "It automatically bridges discrepancies in .shp file and .plt file CRS.\n\n"
            "Risk assessment formulation:\n\n"
            "Chronic cancer risk: R = C * IUR * EC\n"
            "Chronic non-cancer risk: HI = C * (EC/RfC)\n"
            "Acute non-cancer risk: ACUTE = C * (EC/aRfC)\n\n"
            "Where:\n"
            "C - AERPLOT per receptor Concentration at point of exposure\n"
            "IUR - Inhalation unit risk [µg/m³]\n"
            "RfC - Chronic reference concentration [µg/m³]\n"
            "aRfC - Acute reference concentration [µg/m³]\n"
            "EC - Specific Exposure\n\n"
            "EC = (CR*Efg*EF*ED)/(BW*AT*365)\n\n"
            "Where:\n"
            "CR - Contact rate [m³/h]\n"
            "   for Outdoor inhalation CR=Bo(Outdoor vapor inhalation rate)\n"
            "   for Indoor inhalation CR=Bi(Indoor vapor inhalation rate)\n"
            "Efg - Daily frequency [h/d]; Efgo (outdoor); Efgi (indoor) [h/d]\n"
            "EF - Exposure frequency [days/year]\n"
            "ED - Exposure duration [years]\n"
            "BW - Body weight [kg]\n"
            "AT - Averaging time (for carcinogens), for non-carcinogens AT=ED [years]"
        )
        info_text.setFont(QFont('Arial', 10))
        layout.addWidget(info_text)

        self.setLayout(layout)
